# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: none
version = 1

# TODO: replace `WITH LicenseRef` to `WITH AdditionRef` when supported and/or devendor exception when database is updated.

[[annotations]]
path = [
    "tdesktop/cur/*-Yukigram-Build-support.patch",
    "tdesktop/cur/*-Yukigram-AppId.patch",
    "tdesktop/cur/*-Yukigram-Metadata.patch",
    "tdesktop/cur/*-Yukigram-Artwork.patch",
    "tdesktop/cur/*-Yukigram-Version.patch",
    "tdesktop/cur/*-Yukigram-Keywords.patch",
    "tdesktop/cur/*-Yukigram-Options-framework.patch",
    "tdesktop/cur/*-Yukigram-Settings.patch",
    "tdesktop/cur/*-Yukigram-Settings-deep-links.patch",
    "tdesktop/cur/*-Yukigram-Experimental-settings-mirror.patch",
    "tdesktop/cur/*-Fix-Disable-dbus-activation.patch",
    "tdesktop/cur/*-Fix-Opt-Symbolic-tray-icon-from-icon-theme.patch",
    "tdesktop/cur/*-Fix-Support-xdg-data-Yukigram-as-compat-datadir.patch",
    "tdesktop/cur/*-Annoyances-Disable-ads.patch",
    "tdesktop/cur/*-Annoyances-Remove-copy-restrictions.patch",
    "tdesktop/cur/*-Annoyances-Open-location-in-OpenStreetMap.patch",
    "tdesktop/cur/*-Annoyances-Unregister-url-schemes.patch",
    "tdesktop/cur/*-Annoyances-Disable-AI-message-summaries.patch",
    "tdesktop/cur/*-Annoyances-Disable-AI-compose-button-by-default.patch",
    "tdesktop/cur/*-Annoyances-Unshare-phone-number-by-default.patch",
    "tdesktop/cur/*-Annoyances-Send-large-photos-by-default.patch",
    "tdesktop/cur/*-Annoyances-Disable-AI-IV-summaries.patch",
    "tdesktop/cur/*-Minor-tg-nya-handler.patch",
    "tdesktop/cur/*-Shortcut-Immediate-restart.patch",
    "tdesktop/cur/*-Major-Opt-Control-calls-with-MPRIS.patch",
    "tdesktop/cur/*-Minor-More-accounts.patch",
    "tdesktop/cur/*-Shortcut-Forward-Copy-Steal.patch",
    "tdesktop/cur/*-Shortcut-Clickable-links-in-bio.patch",
    "tdesktop/cur/*-Shortcut-Hide-similar-channels-on-join-message-by-de.patch",
    "tdesktop/cur/*-Shortcut-Hide-Join-group-button-in-open-groups.patch",
    "tdesktop/cur/*-Shortcut-Open-group-from-peer-info.patch",
    "tdesktop/cur/*-Info-Show-mutual-contacts.patch",
    "tdesktop/cur/*-Info-Show-media-DC.patch",
    "tdesktop/cur/*-Info-Show-more-session-info.patch",
    "tdesktop/cur/*-Minor-Additional-emoji-aliases.patch",
    "tdesktop/cur/*-Message-Opt-Disable-animoji.patch",
    "tdesktop/cur/*-Message-Opt-Right-action-comments.patch",
    "tdesktop/cur/*-Interface-Opt-Single-column-layout.patch",
    "tdesktop/cur/*-Style-Opt-Wide-messages.patch",
    "tdesktop/cur/*-Compose-Opt-Show-scheduled-messages-button.patch",
    "tdesktop/cur/*-Style-Increase-max-media-sizes.patch",
    "tdesktop/cur/*-Message-unofficial-client-user-peer-type-icon.patch",
    "tdesktop/cur/*-Style-Opt-Hide-per-chat-wallpaper.patch",
    "tdesktop/cur/*-Interface-Opt-Compact-chat-list.patch",
    "tdesktop/cur/*-Compose-Opt-Hide-Send-As-premium-channels.patch",
    "tdesktop/cur/*-Compose-Opt-Hide-Send-As-button.patch",
    "tdesktop/cur/*-Chat-Statistics-button-in-menu.patch",
    "tdesktop/cur/*-Style-Opt-Hide-reply-background-emoji.patch",
    "tdesktop/cur/*-Interface-Sensible-peer-id-and-join-date-rendering.patch",
    "tdesktop/cur/*-Info-Opt-Show-inferred-peer-DC.patch",
    "tdesktop/cur/*-Reactions-Opt-Hide-Star-reaction-on-no-message-stars.patch",
    "tdesktop/cur/*-Reactions-Opt-Hide-Star-reaction-count-completely.patch",
    "tdesktop/cur/*-Style-Opt-Hide-message-tail.patch",
    "tdesktop/cur/*-Interface-Opt-System-emoji.patch",
    "tdesktop/cur/*-Interface-Opt-Custom-monospace-font.patch",
    "tdesktop/cur/*-Compose-Opt-Hide-popular-stickers-in-suggested.patch",
    "tdesktop/cur/*-Compose-Opt-Hide-popular-custom-emoji-in-picker.patch",
    "tdesktop/cur/*-Fix-Webview-socket-path.patch",
    "tdesktop/cur/*-Style-Revert-Added-pill-design-to-top-bar-suggestion.patch",
    "tdesktop/cur/*-Fix-Appstream-changelog.patch",
    "tdesktop/cur/*-Yukigram-Changelog.patch",
    "tdesktop/cur/*-Major-Split-Stickers-and-GIFs-chat-permission-toggle.patch",
    "tdesktop/cur/*-Fix-Ignore-old-tdesktop-tdata.patch",
    "tdesktop/cur/*-Info-Warn-when-polls-forbid-revoting.patch",
    "tdesktop/cur/*-Minor-Peer-info-apply-join-button.patch",
    "tdesktop/cur/*-Chat-Opt-Hide-bottom-button-bar.patch",
    "tdesktop/cur/*-Fix-Non-admin-monoforum-button-in-menu.patch",
    "tdesktop/cur/*-Style-Opt-Old-style-spoilers.patch",
    "tdesktop/cur/*-Style-Fix-button-rounding-in-history-top-bar.patch",
    "tdesktop/cur/*-Style-Fix-button-rounding-in-bot-keyboard.patch",
    "tdesktop/cur/*-Interface-Opt-Disable-shouting-case-on-buttons.patch",
]
SPDX-License-Identifier = "GPL-3.0-or-later WITH LicenseRef-sqlitestudio-OpenSSL-exception"
SPDX-FileCopyrightText = "Yukigram contributors <https://github.com/yukigram/yukigram>"

[[annotations]]
path = [
    "tdesktop/cur/*-Major-Handle-tg-openmessage-and-tg-user-links.patch",
    "tdesktop/cur/*-Info-Show-sticker-pack-owner.patch",
    "tdesktop/cur/*-Info-Show-member-join-date.patch",
    "tdesktop/cur/*-Chat-Show-messages-from-user.patch",
    "tdesktop/cur/*-Chat-Show-time-on-service-messages.patch",
    "tdesktop/cur/*-Interface-Opt-Show-time-with-seconds.patch",
    "tdesktop/cur/*-Chat-Recent-actions-button.patch",
    "tdesktop/cur/*-Chat-Admin-list-button.patch",
    "tdesktop/cur/*-Message-Opt-Show-message-id.patch",
    "tdesktop/cur/*-Style-Increase-maxSignatureSize.patch",
    "tdesktop/cur/*-Major-New-Supergroup.patch",
    "tdesktop/cur/*-Chat-Go-to-first-message.patch",
    "tdesktop/cur/*-Major-Mention-users-by-id.patch",
]
SPDX-License-Identifier = "GPL-3.0-or-later WITH LicenseRef-sqlitestudio-OpenSSL-exception"
SPDX-FileCopyrightText = "Yukigram contributors, 64Gram contributors <https://github.com/TDesktop-x64/tdesktop>"

[[annotations]]
path = [
    "tdesktop/cur/*-Info-Always-show-edit-timer.patch",
    "tdesktop/cur/*-Message-Opt-Peer-type-icon-in-history.patch",
    "tdesktop/cur/*-Interface-Video-controls-for-GIFs.patch",
    "tdesktop/cur/*-Chat-Opt-Disable-edit-by-Up-key.patch",
    "tdesktop/cur/*-Info-More-info-in-PeerListBox.patch",
    "tdesktop/cur/*-Info-More-info-in-filtered-chats.patch",
]
SPDX-License-Identifier = "GPL-3.0-or-later WITH LicenseRef-sqlitestudio-OpenSSL-exception"
SPDX-FileCopyrightText = "Yukigram contributors, Kotatogram contributors <https://github.com/kotatogram/kotatogram-desktop>"

[[annotations]]
path = [
    "tdesktop/cur/*-Message-Show-forwarded-message-date.patch",
]
SPDX-License-Identifier = "GPL-3.0-or-later WITH LicenseRef-sqlitestudio-OpenSSL-exception"
SPDX-FileCopyrightText = "Yukigram contributors, Forkgram contributors <https://github.com/forkgram/tdesktop>"

[[annotations]]
path = [
    ".gitignore",
    ".mailmap",
    "npins/sources.json",
    "*.md",
]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "none"

[[annotations]]
path = [
    "*.nix",
    "hooks/*",
    "s/*",
]
SPDX-License-Identifier = "CC0-1.0 OR Unlicense"
SPDX-FileCopyrightText = "Yukigram contributors"

[[annotations]]
path = "npins/default.nix"
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "npins contributors <https://github.com/andir/npins>"

[[annotations]]
path = [".github/workflows/*.yml", "flatpak/io.github.yukigram.yml"]
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "Yukigram contributors"
