# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: none
version = 1

# TODO: replace `WITH LicenseRef` to `WITH AdditionRef` when supported and/or devendor exception when database is updated.

[[annotations]]
path = [
    "tdesktop/cur/*-Yukigram-branding.patch",
    "tdesktop/cur/*-Yukigram-build-support.patch",
    "tdesktop/cur/*-Yukigram-options-framework.patch",
    "tdesktop/cur/*-Yukigram-settings.patch",
    "tdesktop/cur/*-tg-nya-handler.patch",
    "tdesktop/cur/*-Disable-sponsored-messages.patch",
    "tdesktop/cur/*-Immediate-restart-button.patch",
    "tdesktop/cur/*-Allow-disabling-animoji.patch",
    "tdesktop/cur/*-Support-post-comments-button-as-right-action.patch",
    "tdesktop/cur/*-Control-calls-with-MPRIS.patch",
    "tdesktop/cur/*-Remove-copy-restrictions.patch",
    "tdesktop/cur/*-Allow-forcing-single-column-layout.patch",
    "tdesktop/cur/*-Open-location-in-OpenStreetMap.patch",
    "tdesktop/cur/*-Support-wide-messages.patch",
    "tdesktop/cur/*-Allow-more-accounts.patch",
    "tdesktop/cur/*-Always-show-scheduled-messages-button.patch",
    "tdesktop/cur/*-Disable-AI-summaries-on-messages.patch",
    "tdesktop/cur/*-Unregister-url-schemes.patch",
    "tdesktop/cur/*-Increase-max-media-sizes.patch",
    "tdesktop/cur/*-Forward-Copy-Steal-shortcuts.patch",
    "tdesktop/cur/*-Disable-AI-compose-button-by-default.patch",
    "tdesktop/cur/*-Disable-dbus-activation.patch",
    "tdesktop/cur/*-Unshare-phone-number-by-default-on-adding-contact.patch",
    "tdesktop/cur/*-Clickable-links-in-bio.patch",
    "tdesktop/cur/*-Show-unofficial-client-users-in-chat.patch",
    "tdesktop/cur/*-Hide-similar-channels-on-join-message-by-default.patch",
    "tdesktop/cur/*-Hide-Join-group-button-in-open-groups.patch",
    "tdesktop/cur/*-Hide-per-chat-wallpaper.patch",
    "tdesktop/cur/*-Allow-opening-group-from-peer-info.patch",
    "tdesktop/cur/*-Compact-chat-list.patch",
    "tdesktop/cur/*-Symbolic-tray-icon-from-icon-theme.patch",
]
SPDX-License-Identifier = "GPL-3.0-only WITH LicenseRef-sqlitestudio-OpenSSL-exception"
SPDX-FileCopyrightText = "Yukigram contributors <https://github.com/yukigram/yukigram>"

[[annotations]]
path = [
    "tdesktop/cur/*-Handle-tg-openmessage-and-tg-user-links.patch",
    "tdesktop/cur/*-Show-messages-from-user.patch",
    "tdesktop/cur/*-Show-time-on-service-messages.patch",
    "tdesktop/cur/*-Show-time-with-seconds.patch",
    "tdesktop/cur/*-Show-sticker-pack-owner.patch",
    "tdesktop/cur/*-Quick-Recent-Actions-button.patch",
    "tdesktop/cur/*-Quick-Admin-list-button.patch",
    "tdesktop/cur/*-Show-message-id.patch",
    "tdesktop/cur/*-Increase-maxSignatureSize.patch",
    "tdesktop/cur/*-Show-member-join-date.patch",
]
SPDX-License-Identifier = "GPL-3.0-only WITH LicenseRef-sqlitestudio-OpenSSL-exception"
SPDX-FileCopyrightText = "Yukigram contributors, 64Gram contributors <https://github.com/TDesktop-x64/tdesktop>"

[[annotations]]
path = [
    "tdesktop/cur/*-Show-user-type-icon-in-username-in-chat.patch",
    "tdesktop/cur/*-Always-show-edit-timer.patch",
]
SPDX-License-Identifier = "GPL-3.0-only WITH LicenseRef-sqlitestudio-OpenSSL-exception"
SPDX-FileCopyrightText = "Yukigram contributors, Kotatogram contributors <https://github.com/kotatogram/kotatogram-desktop>"

[[annotations]]
path = [
    "tdesktop/cur/*-Show-forwarded-message-date.patch",
]
SPDX-License-Identifier = "GPL-3.0-only WITH LicenseRef-sqlitestudio-OpenSSL-exception"
SPDX-FileCopyrightText = "Yukigram contributors, Forkgram contributors <https://github.com/forkgram/tdesktop>"

[[annotations]]
path = [
    ".gitignore",
    ".mailmap",
    "npins/sources.json",
    "CONTRIBUTING.md",
    "README.md",
]
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "none"

[[annotations]]
path = [
    "*.nix",
    "hooks/*",
]
SPDX-License-Identifier = "CC0-1.0 OR Unlicense"
SPDX-FileCopyrightText = "Yukigram contributors"

[[annotations]]
path = "npins/default.nix"
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "npins contributors <https://github.com/andir/npins>"

[[annotations]]
path = [".github/workflows/*.yml", "flatpak/io.github.yukigram.yml"]
SPDX-License-Identifier = "MIT"
SPDX-FileCopyrightText = "Yukigram contributors"
