name: Binary cache
on:
  push:
    tags:
      - "v*"
      - "!v*-*"
  workflow_dispatch:
    inputs:
      short_run:
        description: 'Do a short run instead of normal one (10 minutes)'
        type: boolean
permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  binary:
    timeout-minutes: ${{ inputs.short_run && 10 || 360 }}
    name: Linux binary
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone yukigram
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          path: yukigram

      - name: Clone tdesktop
        uses: actions/checkout@v6
        with:
          repository: telegramdesktop/tdesktop
          ref: 6e90f6876e2a2daf04d97ea97345cc9ad8ade378 # v6.7.8 tag is not published yet
          path: yukigram-worktree
          submodules: recursive

      - name: Fix cloned repositories
        run: |
          set -exuo pipefail
          git config --global --add safe.directory yukigram
          git config --global --add safe.directory yukigram-worktree

      - name: Patch patches
        run: |
          set -exuo pipefail
          pushd yukigram
          commit=$(git describe --abbrev=12 HEAD)
          sed -i s/@commit/$commit/ tdesktop/cur/0001-Yukigram-branding.patch
          popd

      - name: Apply patches
        env:
          GIT_COMMITTER_NAME: "Automated builder commit"
          GIT_COMMITTER_EMAIL: "<noreply@example.com>"
        run: |
          set -exuo pipefail
          pushd yukigram-worktree
          git am ../yukigram/tdesktop
          popd

      - name: Build
        run: |
          set -exuo pipefail
          pushd yukigram-worktree
          ./build.sh
          popd

      - name: Install
        run: |
          set -exuo pipefail
          pushd yukigram-worktree
          ./install.sh
          popd

      - name: Save architecture
        run: |
          set -exuo pipefail
          echo ARCH="$(uname -m)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: binary-${{ env.ARCH }}
          path: yukigram-worktree/app


  flatpak:
    needs: [binary]
    name: Flatpak repository
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64]

    steps:
      - name: Prepare flatpak-builder
        run: |
          set -exuo pipefail
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: binary-${{ matrix.arch }}
          path: yukigram-worktree/app

      - name: Clone yukigram
        uses: actions/checkout@v6
        with:
          path: yukigram

      - name: Change appId
        if: github.event_name == 'workflow_dispatch'
        run: |
          sed s/io.github.yukigram/io.github.yukigram.devel/ yukigram/flatpak/io.github.yukigram.yml

      - name: Build
        run: |
          set -exuo pipefail
          pushd yukigram/flatpak
          flatpak-builder --user \
            --install-deps-from=flathub \
            --disable-rofiles-fuse \
            --force-clean \
            --repo=repo \
            --arch=${{ matrix.arch }} \
            build_dir \
            io.github.yukigram.yml
          popd

      - name: Generate index.flatpakrepo
        run: |
          cat >yukigram/flatpak/repo/index.flatpakrepo <<EOF
          [Flatpak Repo]
          Title=Yukigram
          Description=Patched Telegram Desktop
          Url=https://yukigram.github.io/yukigram
          Homepage=https://t.me/yukigram
          Icon=https://raw.githubusercontent.com/flatpak/flatpak/main/flatpak.png
          EOF

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: flatpak-${{ matrix.arch }}
          path: yukigram/flatpak/repo

  nixos:
    timeout-minutes: ${{ inputs.short_run && 10 || 360 }}
    name: NixOS binary cache build
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34

      - name: Clone
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build packages
        env:
          NIX_BINARY_CACHE_KEY: ${{ secrets.NIX_BINARY_CACHE_KEY }}
        run: |
          set -exuo pipefail

          export NIX_PATH=nixpkgs=$(nix-shell -I nixpkgs=channel:nixos-unstable -E 'with import <nixpkgs> {}; mkShellNoCC { packages = [npins]; }' --run 'npins get-path nixpkgs')

          nix-build -j0 --keep-going || true
          find /nix/store -maxdepth 1 -mindepth 1 | sort > paths-from-nixos-cache.txt
          nix-build -E 'with import <nixpkgs> {}; closureInfo { rootPaths = [ (import ./. {}) ]; }'

          echo "$NIX_BINARY_CACHE_KEY" > bincache-key.priv
          nix --extra-experimental-features nix-command key convert-secret-to-public < bincache-key.priv > bincache-key.pub

          nix-shell -p nix-serve --run 'NIX_SECRET_KEY_FILE=$PWD/bincache-key.priv nix-serve &'
          while ! curl http://127.0.0.1:5000/; do sleep 1; done

          mkdir -p out/nar
          wget http://127.0.0.1:5000/nix-cache-info -O out/nix-cache-info
          comm -13 paths-from-nixos-cache.txt result/store-paths | sed 's:/nix/store/\([^-]*\)-.*:\1:' | while read path; do
            wget http://127.0.0.1:5000/$path.narinfo -O out/$path.narinfo
            nar="$(grep '^URL: ' out/$path.narinfo | cut -d ' ' -f 2-2)"
            wget http://127.0.0.1:5000/$nar -O out/$nar
          done

          FLAKE='(builtins.getFlake "git+file://'$(pwd)'?rev=${{ github.sha }}")'
          nix-hash --to-base32 "$(nix --extra-experimental-features 'nix-command flakes' eval --raw --expr "$FLAKE.narHash")" > out/narHash
          cp bincache-key.pub out/narPublicKey

          echo ARCH="$(uname -m)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: nixos-${{ env.ARCH }}
          path: out

  website:
    if: github.event_name != 'workflow_dispatch'
    name: Website for hosting the repositories
    needs: [binary, flatpak, nixos]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v8
        name: Download artifacts

      - name: Prepare website structure
        run: |
          set -exuo pipefail

          mkdir website
          for i in nixos-x86_64 nixos-aarch64 flatpak-x86_64; do
            cp -r $i/. website/
          done

          cat > website/index.html << EOF
          <html>
          <head>
          <title>Yukigram builds</title>
          <meta charset="utf-8"/>
          </head>
          <body>
          <h1>Yukigram builds for NixOS</h1>
          <p>Specify <code>git+https://github.com/${{ github.event.repository.full_name }}</code> as the input URL in your flake.</p>
          <p>Alternatively, you can import the Yukigram package on a non-flake system as follows:</p>
          <pre>import (fetchFromGitHub {
            owner = "yukigram";
            repo = "yukigram";
            rev = "${{ github.sha }}";
            sha256 = "$(cat website/narHash)";
          }) {}</pre>
          <h2>Binary cache</h2>
          <p>To use the binary cache, specify <code>https://yukigram.github.io/yukigram</code> as an extra substituter, and <code>$(cat website/narPublicKey)</code> as an extra trusted key. Note that the binary cache is only provided for the Nixpkgs version pinned in the flake.</p>
          <h1>Yukigram flatpak repository</h1>
          <pre>flatpak remote-add --user --if-not-exists yukigram https://yukigram.github.io/yukigram/index.flatpakrepo
          flatpak install io.github.yukigram</pre>
          </body>
          </html>
          EOF
          rm -f website/narHash website/narPublicKey

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: website

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v5
