name: Binary cache
on:
  push:
    tags:
      - "v*"
      - "!v*-*"
  workflow_dispatch:
    inputs:
      override_github_pages:
        description: 'Override Pages artifact (dangerous!)'
        type: boolean
      short_run:
        description: 'Short run (10 minutes limit)'
        type: boolean
      push_to_cachix:
        description: 'Push builds to cachix'
        type: boolean
      disable_binary:
        description: 'Disable static binary build'
        type: boolean
      disable_nixos:
        description: 'Disable nix build'
        type: boolean
      disable_pmos:
        description: 'Disable postmarketOS build'
        type: boolean
      prerelease:
        description: 'Mark as pre-release'
        type: boolean
permissions:
  attestations: write
  contents: write
  pages: write
  id-token: write

jobs:

  binary:
    timeout-minutes: ${{ inputs.short_run && 10 || 360 }}
    if: ${{ ! inputs.disable_binary }}
    name: Linux binary
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone yukigram
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          path: yukigram

      - name: Clone tdesktop
        uses: actions/checkout@v6
        with:
          repository: telegramdesktop/tdesktop
          ref: v7.0.1
          path: yukigram-worktree
          submodules: recursive

      - name: Fix cloned repositories
        run: |
          set -exuo pipefail
          git config --global --add safe.directory yukigram
          git config --global --add safe.directory yukigram-worktree

      - name: Patch patches
        run: |
          set -exuo pipefail
          pushd yukigram
          commit=$(git describe --abbrev=12 HEAD)
          sed -i s/@commit/$commit/ tdesktop/cur/*-Yukigram-Version.patch
          popd

      - name: Apply patches
        run: |
          set -exuo pipefail
          pushd yukigram-worktree
          for p in ../yukigram/tdesktop/cur/*.patch; do
            printf '==== %s ====\n' "$p"
            patch -p1 <"$p"
          done
          popd

      - name: Use .devel appId
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo DEVEL=true >> $GITHUB_ENV

      - name: Build
        run: |
          set -exuo pipefail
          pushd yukigram-worktree
          ./build.sh
          popd

      - name: Install
        run: |
          set -exuo pipefail
          pushd yukigram-worktree
          ./install.sh --prefix /app
          popd

      - name: Save architecture
        run: |
          set -exuo pipefail
          echo ARCH="$(uname -m)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: binary-${{ env.ARCH }}
          path: yukigram-worktree/app


  flatpak:
    needs: [binary]
    name: Flatpak repository
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64]

    steps:
      - name: Prepare flatpak-builder
        run: |
          set -exuo pipefail
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Download artifact
        uses: actions/download-artifact@v8
        with:
          name: binary-${{ matrix.arch }}
          path: yukigram-worktree/app

      - name: Clone yukigram
        uses: actions/checkout@v6
        with:
          path: yukigram

      - name: Setup GPG
        id: gpg
        uses: crazy-max/ghaction-import-gpg@v7
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Build
        run: |
          set -exuo pipefail
          pushd yukigram/flatpak
          flatpak-builder --user \
            --install-deps-from=flathub \
            --disable-rofiles-fuse \
            --force-clean \
            --repo=repo \
            --arch=${{ matrix.arch }} \
            --gpg-sign=${{ steps.gpg.outputs.fingerprint }} \
            build_dir \
            io.github.yukigram.yml
          popd

      - name: Generate index.flatpakrepo
        run: |
          cat >yukigram/flatpak/repo/index.flatpakrepo <<EOF
          [Flatpak Repo]
          Title=Yukigram
          Description=Patched Telegram Desktop
          Url=https://yukigram.github.io/yukigram
          Homepage=https://t.me/yukigram
          Icon=https://raw.githubusercontent.com/flatpak/flatpak/main/flatpak.png
          GPGKey=$(gpg2 --armor --export ${{ steps.gpg.outputs.fingerprint }} | sed -E '/-----|^=/d' | tr -d '\n')
          EOF

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: flatpak-${{ matrix.arch }}
          path: yukigram/flatpak/repo

  postmarketos:
    timeout-minutes: ${{ inputs.short_run && 10 || 360 }}
    if: ${{ ! inputs.disable_pmos }}
    name: PostmarketOS build
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        arch: [x86_64, aarch64, armv7]

    steps:
      - name: Clone
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install pmbootstrap
        run: |
          set -exuo pipefail

          sudo apt-get install python3-pip python3-virtualenv
          virtualenv .
          . bin/activate
          pip3 install tomli
          pip3 install https://gitlab.postmarketos.org/postmarketOS/pmbootstrap/-/archive/main.tar.gz

      - name: pmbootstrap init
        run: |
          set -exuo pipefail

          . bin/activate
          yes '' | pmbootstrap init || true
          pmbootstrap config service_manager openrc
          pmbootstrap config mirrors.systemd none

      - name: Prepare private key
        env:
          ABUILD_PRIVATE_KEY: ${{ secrets.ABUILD_PRIVATE_KEY }}
        run: |
          set -exuo pipefail

          sudo rm -rf ~/.local/var/pmbootstrap/config_abuild
          mkdir ~/.local/var/pmbootstrap/config_abuild
          echo "$ABUILD_PRIVATE_KEY" > ~/.local/var/pmbootstrap/config_abuild/yukigram.github.io.rsa
          openssl rsa -in ~/.local/var/pmbootstrap/config_abuild/yukigram.github.io.rsa -pubout > ~/.local/var/pmbootstrap/config_abuild/yukigram.github.io.rsa.pub
          echo 'PACKAGER_PRIVKEY="/home/pmos/.abuild/yukigram.github.io.rsa"' > ~/.local/var/pmbootstrap/config_abuild/abuild.conf
          mkdir -p ~/.local/var/pmbootstrap/config_apk_keys
          sudo cp ~/.local/var/pmbootstrap/config_abuild/yukigram.github.io.rsa.pub ~/.local/var/pmbootstrap/config_apk_keys

      - name: Prepare ports tree
        run: |
          set -exuo pipefail

          . bin/activate
          pmbootstrap pull
          ln -s ~/.local/var/pmbootstrap/cache_git/pmaports pmaports

      - name: Prepare package yukigram-key
        run: |
          set -exuo pipefail

          mkdir pmaports/temp/yukigram-key
          cat > pmaports/temp/yukigram-key/APKBUILD << EOF
          pkgname=yukigram-key
          pkgver=2
          pkgrel=0
          pkgdesc="Public key for the Yukigram repository"
          url="https://yukigram.github.io"
          arch="noarch"
          license="MIT"
          source="yukigram.github.io.rsa.pub"
          options="!check"

          package() {
              install -Dm644 "\$srcdir"/yukigram.github.io.rsa.pub "\$pkgdir"/etc/apk/keys/yukigram.github.io.rsa.pub
              install -Dm644 "\$srcdir"/yukigram.github.io.rsa.pub "\$pkgdir"/usr/share/apk/keys/yukigram.github.io.rsa.pub
          }
          EOF
          cp ~/.local/var/pmbootstrap/config_abuild/yukigram.github.io.rsa.pub pmaports/temp/yukigram-key/

      - name: Get package version
        run: |
          set -exuo pipefail

          if git describe --exact-match HEAD; then
            # tagged version
            pkgver=$(git describe HEAD)
            pkgver=${pkgver/-beta/_beta}
            pkgver=${pkgver/-rc./_rc}
            pkgrel=0
          else
            # git version
            date=$(git show --pretty='%cs' --no-patch)
            date=${date//-/}
            tag=$(git describe --abbrev=0 HEAD)
            pkgver=${tag/-*/}_git${date} # replace semver suffixes
            pkgrel=$(git rev-list --count $tag..)
          fi
          pkgver=${pkgver/v/} # strip tag prefix (v6.8.2.2 -> 6.8.2.2)

          echo pkgver=$pkgver >> $GITHUB_ENV
          echo pkgrel=$pkgrel >> $GITHUB_ENV

      - name: Prepare package yukigram
        run: |
          set -exuo pipefail

          . bin/activate
          pmbootstrap aportgen --fork-alpine telegram-desktop
          mv pmaports/temp/telegram-desktop pmaports/temp/yukigram

          additional_sources=$(printf 'source="$source %s"\n' tdesktop/cur/*.patch)
          additional_sha512sums=$(sha512sum tdesktop/cur/*.patch)
          cp -r tdesktop pmaports/temp/yukigram/

          # Remove libdispatch fix (6.9.4)
          sed -i '/fix-dispatch-desktop_app_skip_libs.patch/d' pmaports/temp/yukigram/APKBUILD

          cat >> pmaports/temp/yukigram/APKBUILD << EOF

          pkgname=yukigram
          builddir="\${builddir/\$pkgver/__pkgver__}"
          pkgver=7.0.1 # Upstream version
          pkgdesc="Yukigram (Telegram Desktop fork) messaging app"
          makedepends="\$makedepends minizip-dev zlib-dev"
          source="\${source/https:*-full.tar.gz/https://github.com/telegramdesktop/tdesktop/releases/download/v\$pkgver/tdesktop-\$pkgver-full.tar.gz}"
          builddir="\${builddir/__pkgver__/\$pkgver}"
          pkgver=$pkgver # Yukigram version
          pkgrel=$pkgrel
          $additional_sources
          sha512sums="\$sha512sums
          $additional_sha512sums"
          unset maintainer
          EOF

      - name: Build package yukigram
        run: |
          set -exuo pipefail
          . bin/activate
          pmbootstrap --details-to-stdout checksum yukigram
          pmbootstrap --details-to-stdout build --arch=${{ matrix.arch }} yukigram

      - name: Build package yukigram-key
        run: |
          set -exuo pipefail
          . bin/activate
          pmbootstrap --details-to-stdout checksum yukigram-key
          pmbootstrap --details-to-stdout build --arch=${{ matrix.arch }} yukigram-key

      - name: Save APKBUILD files
        run: |
          set -exuo pipefail
          cd ~/.local/var/pmbootstrap
          mkdir pmaports
          mv ~/.local/var/pmbootstrap/cache_git/pmaports/temp/yukigram* pmaports/

      - name: Create unversioned .apk symlinks
        run: |
          set -exuo pipefail
          cd ~/.local/var/pmbootstrap/packages/edge/${{ matrix.arch }}
          echo yukigram-$pkgver-r$pkgrel.apk | sudo tee yukigram.apk.link

      - uses: actions/upload-artifact@v7
        name: Upload artifact
        with:
          name: postmarketos-${{ matrix.arch }}
          path: |
            ~/.local/var/pmbootstrap/pmaports
            ~/.local/var/pmbootstrap/packages

  nixos:
    timeout-minutes: ${{ inputs.short_run && 10 || 360 }}
    if: ${{ ! inputs.disable_nixos }}
    name: NixOS binary cache build
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v34

      - name: Clone
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup NIX_PATH
        run: |
          set -exuo pipefail
          echo NIX_PATH=nixpkgs=$(nix-instantiate --eval --raw ./. -A sources.nixpkgs.outPath) >> $GITHUB_ENV

      - name: Fetch dependencies from caches
        run: |
          set -exuo pipefail
          nix-build -A packages.default -j0 --keep-going || true
          find /nix/store -maxdepth 1 -mindepth 1 | sort > paths-from-nixos-cache.txt

      - name: Build packages
        run: |
          set -exuo pipefail
          nix-build -E 'with import <nixpkgs> {}; closureInfo { rootPaths = [ (import ./. {}).packages.nonisolated.unwrapped ]; }'

      - name: Filter out substitutable paths
        run: |
          set -exuo pipefail
          comm -13 paths-from-nixos-cache.txt result/store-paths >built-paths

      - name: Convert private key
        env:
          NIX_BINARY_CACHE_KEY: ${{ secrets.NIX_BINARY_CACHE_KEY }}
        run: |
          set -exuo pipefail
          echo "$NIX_BINARY_CACHE_KEY" > bincache-key.priv
          nix --extra-experimental-features nix-command key convert-secret-to-public < bincache-key.priv > bincache-key.pub

      - name: Create local binary cache
        run: |
          set -exuo pipefail

          nix-shell -p nix-serve --run 'NIX_SECRET_KEY_FILE=$PWD/bincache-key.priv nix-serve &'
          while ! curl http://127.0.0.1:5000/; do sleep 1; done

          mkdir -p out/nar
          wget http://127.0.0.1:5000/nix-cache-info -O out/nix-cache-info
          <built-paths sed 's:/nix/store/\([^-]*\)-.*:\1:' | while read path; do
            wget http://127.0.0.1:5000/$path.narinfo -O out/$path.narinfo
            nar="$(grep '^URL: ' out/$path.narinfo | cut -d ' ' -f 2-2)"
            wget http://127.0.0.1:5000/$nar -O out/$nar
          done

          cp bincache-key.pub out/narPublicKey
          rm bincache-key.priv

      - name: Save yukigram narHash
        run: |
          set -exuo pipefail
          FLAKE='(builtins.getFlake "git+file://'$(pwd)'?rev=${{ github.sha }}")'
          nix-hash --to-base32 "$(nix --extra-experimental-features 'nix-command flakes' eval --raw --expr "$FLAKE.narHash")" > out/narHash

      - name: Push to cachix
        if: github.event_name != 'workflow_dispatch' || inputs.push_to_cachix
        env:
          CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
          CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
        run: |
          set -exuo pipefail
          nix-shell -p cachix --run 'cachix push yukigram-official' <built-paths

      - name: Save architecture
        run: |
          set -exuo pipefail
          echo ARCH="$(uname -m)" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: nixos-${{ env.ARCH }}
          path: out

  website:
    if: github.event_name != 'workflow_dispatch' || inputs.override_github_pages
    name: Website for hosting the repositories
    needs: [flatpak, postmarketos, nixos]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v8
        name: Download artifacts

      - name: Prepare website structure
        run: |
          set -exuo pipefail

          mkdir website
          for i in nixos-{x86_64,aarch64} flatpak-x86_64 postmarketos-{x86_64,aarch64,armv7}; do
            cp -r $i/. website/
          done
          for p in website/packages/edge/*/; do
            cp $p/$(< $p/yukigram.apk.link) $p/yukigram.apk
          done

          cat > website/index.html << EOF
          <html>
          <head>
          <title>Yukigram builds</title>
          <meta charset="utf-8"/>
          </head>
          <body>
          <h1>Yukigram builds for NixOS</h1>
          <p>Specify <code>github:${{ github.event.repository.full_name }}/${{ github.sha }}</code> as the input URL in your flake.</p>
          <p>Alternatively, you can import the Yukigram package on a non-flake system as follows:</p>
          <pre>import (fetchFromGitHub {
            owner = "yukigram";
            repo = "yukigram";
            rev = "${{ github.sha }}";
            sha256 = "$(cat website/narHash)";
          }) {}</pre>
          <h2>Binary cache</h2>
          <p>To use the binary cache, specify <code>https://yukigram.github.io/yukigram</code> as an extra substituter, and <code>$(cat website/narPublicKey)</code> as an extra trusted key. Note that the binary cache is only provided for the Nixpkgs version pinned in the flake.</p>
          </body>
          </html>
          EOF
          rm -f website/narHash website/narPublicKey

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: website

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v5

  release-branch:
    name: Update release branch
    needs: [website]
    runs-on: ubuntu-latest

    steps:
      - name: Clone yukigram
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Update branch
        run: |
          set -exuo pipefail
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git switch release
          git reset --hard ${{ github.ref_name }}
          git push --force

  beta-branch:
    name: Update beta branch
    needs: [release]
    if: github.ref_type == 'tag' && inputs.prerelease
    runs-on: ubuntu-latest

    steps:
      - name: Clone yukigram
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Update branch
        run: |
          set -exuo pipefail
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git switch beta
          git reset --hard ${{ github.ref_name }}
          git push --force

  release:
    name: Release artifacts
    if: github.ref_type == 'tag'
    needs: [binary, flatpak, postmarketos, nixos]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8

      - name: Fix binary permissions
        run: |
          set -exuo pipefail

          for d in binary-x86_64; do
            pushd $d
              chmod +x bin/io.github.yukigram*
            popd
          done

      - name: Prepare output directory
        run: |
          set -exuo pipefail
          mkdir out

      - name: Extract postmarketOS apk files
        run: |
          set -exuo pipefail

          for arch in x86_64 aarch64 armv7; do
            p=postmarketos-$arch/packages/edge/$arch/
            cp $p/$(< $p/yukigram.apk.link) out/yukigram-$arch.apk
          done

      - name: Pack artifacts
        run: |
          set -exuo pipefail
          shopt -s dotglob # to pack hidden top-level files
          for a in nixos-{x86_64,aarch64} {binary,flatpak}-x86_64 postmarketos-{x86_64,aarch64,armv7}; do
            pushd $a
              tar czf ../out/$a.tar.gz *
            popd
          done

      - name: Generate artifact attestations
        uses: actions/attest@v4
        with:
          subject-path: out

      - name: Publish
        uses: ncipollo/release-action@v1
        with:
          artifacts: "out/*"
          prerelease: ${{ inputs.prerelease }}
          immutableCreate: true
