name: "Nix build"
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          clean: false
      - name: Install nix
        uses: cachix/install-nix-action@v27
      - name: Magic cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Setup cachix
        uses: cachix/cachix-action@v15
        with:
          name: yukigram
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build
        run: nix build '.?submodules=1#yukigram' -L
